Getting error in pafy.get_playlist() method
Hello everybody!
I'm working on a playlist downloader app and I've got a problem in def playlist_Download(self): with code

#playlist = pafy.get_playlist(playlist_url)

&

#playlist2 = pafy.get_playlist2(playlist_url

When I click on Download click in the app I get this message by using playlist function:

urllib.error.HTTPError: HTTP Error 404: Not Found

and this message by using playlist2 function:

pafy.util.GdataError: Youtube Error 403: The request cannot be completed because you have exceeded your quota. Is there anyone who can help me?